# Generated by Django 2.2.16 on 2020-10-19 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da IES')),
            ],
        ),
        migrations.AddField(
            model_name='setor',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Orgao'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='nome_orgao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do orgão'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome_setor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do setor'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do setor')),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Instituicao')),
            ],
        ),
    ]
