# Generated by Django 2.2.16 on 2020-09-18 19:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estagiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estagiario', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('email_estagiario', models.EmailField(max_length=254, verbose_name='Email')),
                ('dt_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('dt_cadastro', models.DateField(default=django.utils.timezone.now, verbose_name='Data de cadastro')),
                ('status_estagiario', models.BooleanField(default=False, verbose_name='Ativo')),
                ('descricao_contrato', models.TextField(verbose_name='Descrição do contrato')),
                ('dt_inicio_contrato', models.DateField(verbose_name='Data de inicio')),
                ('dt_fim_contrato', models.DateField(verbose_name='Data de término')),
                ('instituicao_edu', models.CharField(max_length=200, verbose_name='Instituição de ensino')),
                ('orgao_estagiario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Orgao', verbose_name='Orgão')),
                ('setor_estagiario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Setor', verbose_name='Setor')),
            ],
        ),
    ]
