# Generated by Django 2.2.16 on 2020-09-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='curso',
            field=models.CharField(max_length=200, null=True, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='num_contrato',
            field=models.IntegerField(null=True, verbose_name='Descrição do contrato'),
        ),
    ]
