# Generated by Django 2.2.16 on 2020-09-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0002_auto_20200923_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='num_contrato',
            field=models.IntegerField(null=True, verbose_name='Número do contrato'),
        ),
    ]
