# Generated by Django 2.2.16 on 2020-09-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0004_estagiario_telefone_estagiario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estagiario',
            old_name='email_estagiario',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='estagiario',
            old_name='nome_estagiario',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='estagiario',
            old_name='orgao_estagiario',
            new_name='orgao',
        ),
        migrations.RenameField(
            model_name='estagiario',
            old_name='setor_estagiario',
            new_name='setor',
        ),
        migrations.RenameField(
            model_name='estagiario',
            old_name='status_estagiario',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='estagiario',
            old_name='telefone_estagiario',
            new_name='telefone',
        ),
    ]
