# Generated by Django 2.2.16 on 2020-09-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0005_auto_20200924_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estagiario',
            old_name='descricao_contrato',
            new_name='contrato',
        ),
        migrations.RenameField(
            model_name='estagiario',
            old_name='num_contrato',
            new_name='n_contrato',
        ),
    ]
