# Generated by Django 2.2.16 on 2020-10-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0007_auto_20200924_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='documento',
            field=models.FileField(null=True, upload_to='media', verbose_name='Documento'),
        ),
    ]
