# Generated by Django 3.1.2 on 2020-10-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0007_auto_20200924_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='documento',
            field=models.FileField(null=True, upload_to='.', verbose_name='Documento'),
        ),
    ]
