# Generated by Django 3.1.2 on 2020-10-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0008_estagiario_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='status_off',
            field=models.BooleanField(default=False, verbose_name='Inativo'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='documento',
            field=models.FileField(null=True, upload_to='media', verbose_name='Documento'),
        ),
    ]
