# Generated by Django 2.2.16 on 2020-10-19 18:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0008_estagiario_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estagiario',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='fim_contrato',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='inicio_contrato',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='n_contrato',
        ),
        migrations.AddField(
            model_name='estagiario',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='curso',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='dt_cadastro',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data de cadastro'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='dt_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='instituicao_edu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição de ensino'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Orgao', verbose_name='Orgão'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Setor', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='telefone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.TextField(blank=True, null=True, verbose_name='Descrição do contrato')),
                ('n_contrato', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número do contrato')),
                ('inicio_contrato', models.DateField(blank=True, null=True, verbose_name='Data de inicio')),
                ('fim_contrato', models.DateField(blank=True, null=True, verbose_name='Data de término')),
                ('documento', models.FileField(null=True, upload_to='media', verbose_name='Documento')),
                ('estagiario_nome', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estagiario.Estagiario')),
            ],
        ),
    ]
