# Generated by Django 2.2.16 on 2020-10-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0009_auto_20201019_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='estagiario_nome',
        ),
        migrations.AddField(
            model_name='estagiario',
            name='estagiario_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estagiario.Contrato'),
        ),
    ]
