# Generated by Django 3.1.2 on 2020-10-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0009_auto_20201008_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estagiario',
            name='status_off',
        ),
    ]
