# Generated by Django 2.2.16 on 2020-10-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0010_auto_20201019_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='curso',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='instituicao_edu',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Instituicao', verbose_name='Instituição de ensino'),
        ),
    ]
