# Generated by Django 3.1.2 on 2020-10-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0010_remove_estagiario_status_off'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estagiario',
            old_name='instituicao_edu',
            new_name='instituicao',
        ),
    ]
