# Generated by Django 3.1.2 on 2020-10-15 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_curso_instituicao'),
        ('estagiario', '0011_auto_20201015_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.instituicao', verbose_name='Instituicao'),
        ),
    ]
