# Generated by Django 2.2.16 on 2020-10-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0012_auto_20201019_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
