# Generated by Django 2.2.16 on 2020-10-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0013_auto_20201019_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='contrato',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do contrato'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='documento',
            field=models.FileField(null=True, upload_to='media', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='fim_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Data de término'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='inicio_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Data de inicio'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='n_contrato',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número do contrato'),
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
    ]
